---

sudo: true

dist: xenial

services:
  - docker

language: python
python:
  - '3.7'

cache: pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

# Only execute travis in master, PR to master or tags
branches:
  only:
    - master
    - /^[0-9]*\.[0-9]*\.[0-9]*$/

install:
  - make requirements_test
script:
  - make test

matrix:
  fast_finish: true

jobs:
  include:
    - stage: "tag version"
      if: branch = master AND type != pull_request AND tag IS NOT present
      script:
        - bash .ci/tag_version.sh
      env:
        secure: "MEMH5LAQzxTPypstpGXwqH3wNxgyH9FWd2JhxNnGg730Pw7GtK+QkMexTzzoJCiXmYelbJHD+xeE5IQGprd6OU3/3+p/7fC6XD2hcNyA/IRJFLAdvto/wzGdCRx+BGxqpkyaKxWdrVds9LXtlSrWSUJ6kFeg4uUm2m19BEBZFH5nFpapDQILouLfIbWMN0JCXHhCEoTQVe1N5IqTONXwUBc9UgvVb8UNHlvJv8P2Hg3ckuE0aWbx6lS+fyKN0zOgJrA6Lolrm+M2eYoI3dZVcqdFpBqwPTCF3H6/JKYJnVeGXjKtDbZMd1F8JWNVCvFXLuHqZ1rCnYkNHzZDo8lHL79kzzQ1vZaQ0C6FKagmc3Skc2snddDuRNDeg2xN5QbM4aUquSWHtF3o+USAMjVkANCIZMGhAfpFdmwu4yU8K4DmMy0yG0589nt2we/HdJcbDIxCejPRtvfsUY0aY2rXyBIG82NovCSAzZGIoqSGZI0vrLNrKTtnGNmOb6gff9jdDBk0yY2ejoET9D8nAt1TpNFKMJz6y7skFbf5RQsnGo3SQ4nDIg1kWgSmTEAIrMBqZUGxBCbHwCYMQUhhg2XbTIYWM9KElo2PoH+PQx5ZNYIWvGeZP7gYx9JhmbgD2mAHhUoobCpKNuC4gKXuJydqAo6TpyaRdYaM+VCZMiITqPE="

    - stage: "deploy arm"
      arch: arm64
      script: skip
      if: type != pull_request AND tag IS present
      deploy:
        - provider: script
          script: bash .ci/deploy.sh
          on:
            tags: true
      env:
        secure: "qbb++AinSY+RZnGbVd+ZXP0n9p6ZeWQfR/3HzkXyFXN4IHn95gqxBYUeTQokEUDBJEnzgO5Ga1xTZbg3kHBe3fou2aP6v3GDLXv9vxQdh5L3iRpHZIjXlkaVQ+B2AzwwPKlMEuF8dPskmPUxUN0YchePPE9S+SCSqt7AmYWbpJlOsTnnQpH8SXx1O8wLNaLOHd/Pew/+Ln35AtH/S1w/0ps+KJtvl8HhTGQwUh6BBGg9yjKSY/VFbMJ5BIkc4UCQmoHvwnmwqwDq0nTUvYEBhjoUCSJQGqEr5dBlKxNmJ07g6kEsplShkilKxlkZTWMlwYp1vq1zjXqT25TqiXXrPVO86lQg0giJ74fzoF3Fx06nXwS3oAuX90vc1GJvI3gbkZQ3Jp0FCQWPWMIoNiDxszp7c6Z1l6Dxe2394Y8RogKPi6DomDFBvspqIdhlCwdQKG71arvtzj/b1xGqSnaTSsmJSOW5Vwumog7cGBH+HW0ZXqduanBjGL7QovBE3FTI4xvsc4RnjejYWhsKH/KF6DjqhVcATk+w4i5s2CpJoCEJTjVKPpNN/0DN8wcBCBLqIMQaL9HsEgpz7HsC9OYpV4kFTDzlH0bbDsBPTgGKu5sHReLzoRiHXZKjNiKK69vwuEjGaCIE8XDlq5k4i3L4eL89rZtzrFHM9eucrfMQvXA="

    - stage: "deploy amd64 and manifest"
      script: skip
      if: type != pull_request AND tag IS present
      deploy:
        - provider: script
          script: bash .ci/deploy.sh
          on:
            tags: true
      env:
        secure: "qbb++AinSY+RZnGbVd+ZXP0n9p6ZeWQfR/3HzkXyFXN4IHn95gqxBYUeTQokEUDBJEnzgO5Ga1xTZbg3kHBe3fou2aP6v3GDLXv9vxQdh5L3iRpHZIjXlkaVQ+B2AzwwPKlMEuF8dPskmPUxUN0YchePPE9S+SCSqt7AmYWbpJlOsTnnQpH8SXx1O8wLNaLOHd/Pew/+Ln35AtH/S1w/0ps+KJtvl8HhTGQwUh6BBGg9yjKSY/VFbMJ5BIkc4UCQmoHvwnmwqwDq0nTUvYEBhjoUCSJQGqEr5dBlKxNmJ07g6kEsplShkilKxlkZTWMlwYp1vq1zjXqT25TqiXXrPVO86lQg0giJ74fzoF3Fx06nXwS3oAuX90vc1GJvI3gbkZQ3Jp0FCQWPWMIoNiDxszp7c6Z1l6Dxe2394Y8RogKPi6DomDFBvspqIdhlCwdQKG71arvtzj/b1xGqSnaTSsmJSOW5Vwumog7cGBH+HW0ZXqduanBjGL7QovBE3FTI4xvsc4RnjejYWhsKH/KF6DjqhVcATk+w4i5s2CpJoCEJTjVKPpNN/0DN8wcBCBLqIMQaL9HsEgpz7HsC9OYpV4kFTDzlH0bbDsBPTgGKu5sHReLzoRiHXZKjNiKK69vwuEjGaCIE8XDlq5k4i3L4eL89rZtzrFHM9eucrfMQvXA="
